### PR TITLE
Updated README to use latest function names

### PR DESCRIPTION
**Pull request by emstoudenmire**
Also added test_readme.jl to make sure README code is correct.

### CODE REVIEW

**Comment by mtfishman** [comment]
Could we have `test_readme.jl` automatically pull in the code from the README file?

**Comment by emstoudenmire** [comment]
It's a good idea, I'm just not sure of how to do it. Best I can think of would be code in test_readme.jl which opens README, parses it to get just the code blocks, then uses Julia's `eval` to run these.

**Comment by mtfishman** [comment]
Yeah that sounds reasonable (or instead of `eval`, just generate a new file with just the code in it and `include` that file at the end of `test_readme.jl`). I guess the tricky part may be automatically inserting test statements.

**Comment by mtfishman** [comment]
Although it looks like we could just directly replace `@show` with `@test`.

**Pull request merged**
