### PR TITLE
[NDTensors] Use TensorOperations.jl v5 in tests

### PR DESCRIPTION
**Pull request by kmp5VT**
# Description
TensorOperations.jl just updated their code to work with cuTENSOR 2.0. The package is not yet registered but it is possible to use the latest version if we add the TensorOperations git repo.  This PR is in response to https://github.com/ITensor/ITensors.jl/issues/1476

### CODE REVIEW

**Comment by mtfishman** [comment]
Thanks, I think it is better to wait for the new version to get registered so we can let the package manager install it automatically but this is a good starting point so we're ready for when it is registered.

**Comment by kmp5VT** [comment]
Okay then I will close this PR and wait until there is an update. Thanks!

**Comment by mtfishman** [comment]
We could keep this PR open, but design it so that it will work once the new version of TensorOperations.jl is registered.

**Comment by kmp5VT** [comment]
@mtfishman I checked recently and we should be able to update cuTENSOR and TensorOperations to get this PR merged. I will look into it today

**Comment by mtfishman** [comment]
Thanks!

**Pull request merged**
