### PR TITLE
Error messages for get and set index

### PR DESCRIPTION
**Pull request by emstoudenmire**
This PR adds error checks for calls to ITensor getindex and setindex! with the wrong number of index values.
- Fix erroring tests
- Dimension checks for ITensor get and set index
- Extra check and formatting changes
- Add tests and checklist entry on formatting

### CODE REVIEW

**Comment by mtfishman** [comment]
Maybe better to use dispatch here to ensure there isn't any runtime overhead, for example:
```julia
@propagate_inbounds @inline function _getindex(T::Tensor{<:Any,N}, ivs::Vararg{<:Any,N}) where {N}
  # Implementation
end
```
and then define a fallback version:
```julia
function _getindex(T::Tensor, ivs::Vararg{<:Any,N}) where {N}
  throw(
    DimensionMismatch("$N index values passed to ITensor getindex, expected $(ndims(T))")
  )
end
```

**Comment by emstoudenmire** [comment]
Ok good idea - I can definitely do it that way instead.

So the failing tests include some involving something like `T = emptyITensor()` followed by `T[i=>1,i'=>1] = 1.0` or similar. Are we planning to continue to support this behavior post 0.2? I guess we are at least going to allow empty ITensors to be a "universal zero for addition" but that does leave the separate question of setting elements.

**Comment by mtfishman** [comment]
Actually it looks like the test was supposed to give an error, but now the error is different so just needs to be updated to `DimensionMismatch` from `MethodError`: https://github.com/ITensor/ITensors.jl/blob/f55d05fa4075521e88eacb648d6012a49ef3aa80/test/empty.jl#L49.

**Comment by mtfishman** [comment]
Not sure what the status of `T = emptyITensor(); T[i=>1,i'=>1] = 1.0` will be, I would be in support of adding that.

**Pull request closed without merging**
