### PR TITLE
[Docs] Fix entanglement entropy calculation

### PR DESCRIPTION
**Pull request by mtfishman**
Fix the docs for computing the entanglement entropy, which has been misleading users, see for example https://itensor.discourse.group/t/entanglement-entropy-in-tdvp-calculation/1594.

Also update some code styles in the docs, library code, and examples, like change `noprime!(a)` to `a = noprime(a)`, `orthogonalize!(psi)` to `psi = orthogonalize(psi)`, etc.

### CODE REVIEW

**Comment by mtfishman** [comment]
[test ITensorMPS]

**Comment by mtfishman** [comment]
[test ITensorMPS] [test ITensorGaussianMPS]

**Comment by mtfishman** [comment]
[test ITensorTDVP]

**Comment by emstoudenmire** [comment]
Great

**Pull request merged**
