### PR TITLE
fix a bug about sum of MPOs, and also two minor ones in ./src/mps/pro…

### PR DESCRIPTION
**Pull request by phymann**
To be more logical, I change the type of output tensor at the initial stage rather than in the end.

I also find out two minor bugs in the file `src/mps/projmposum.jl`.

### CODE REVIEW

**Comment by mtfishman** [comment]
Thanks @phymann, could you add a test?

**Comment by phymann** [comment]
> Thanks @phymann, could you add a test?

Sure. A test is added.

**Comment by phymann** [comment]
@mtfishman Hi Matt!

Can you merge this PR into `main` branch?
Currently I am developing several packages (thermal tensor network methods using MPO) based on `ITensors.jl`.
Without this bug fixing, I have to use my own version of `ITensors.jl`, hence my packages can not be registered (since they depend on an unregistered repository)

Thanks!
Junsen

**Comment by mtfishman** [comment]
@phymann sorry for being slow about this. Could you fix the formatting? Once that's fixed I can merge.

**Comment by mtfishman** [comment]
[test ITensors mps]

**Comment by phymann** [comment]
> @phymann sorry for being slow about this. Could you fix the formatting? Once that's fixed I can merge.

Sure, now the formatting issue is fixed.

**Pull request merged**
