### PR TITLE
Remove call to qr in orthogonalize! so it works with qns

### PR DESCRIPTION
**Pull request by mtfishman**

### CODE REVIEW

**Comment by emstoudenmire** [comment]
Would this be a good use case for `factorize`? Because then later we could just upgrade `factorize` for QN ITensors to use QR internally and then this code will automatically speed up from that.

**Comment by emstoudenmire** [comment]
Nice to see Travis is working again too for some reason

**Comment by mtfishman** [comment]
Yes that's a good point, let's do that.

I was wondering if you did something to get it back, but I guess it was just taking a break.

**Comment by mtfishman** [comment]
The test failed because it ran out of time on the mac build (not sure why it took so long...). Besides that, it is passing, I'll merge this.

**Pull request merged**
