### PR TITLE
Lazy `Op` system

### PR DESCRIPTION
**Pull request by mtfishman**
This adds a lazy `Op` system which can be used to replace the type `SiteOp`, `OpTerm`, `MPOTerm`, and `OpSum`.

Roughly speaking, the only types will be `Op` and a lazy evaluation system on top of `Op` based on a type called `Applied`.

Most algebraic rules like addition and multiplication use the `Applied` type, defined in the `LazyApply` module:
```julia
julia> using ITensors.LazyApply: Applied

julia> ex = Applied(sum, [1, 2])
sum(
[1,
2]
)

julia> ex + 3
sum(
[1,
2,
3]
)

julia> 2 * (ex + 3)
sum(
[2,
4,
6]
)

julia> exp(ex + 3)
exp(
sum(
[1,
2,
3]
)
)

julia> typeof(exp(ex + 3))
Applied{typeof(exp), Tuple{Applied{typeof(sum), Tuple{Vector{Int64}}}}}
```
(Obviously printing could be better, but it is currently geared towards making the printing of `Op` objects nicer). You can see some operations compose, like adding a new item to a sum gives a new sum, and multiplying scalars is done eagerly, while other operations are done purely lazily. Again, these choices are geared towards our use case of joining sums of products of scaled `Op`s to make local Hamiltonians.

Here is how the system works with `Op` objects:
```julia
julia> using ITensors

julia> Op("X", 1)
(X, 1)

julia> Op("X", 1) * Op("Y", 2)
(X, 1) * (Y, 2)

julia> typeof(Op("X", 1) * Op("Y", 2))
Applied{typeof(prod), Tuple{Vector{Op}}}

julia> 2.3 * Op("X", 1) * Op("Y", 2)
(2.3) * (X, 1) * (Y, 2)

julia> typeof(2.3 * Op("X", 1) * Op("Y", 2))
Applied{typeof(*), Tuple{Float64, Applied{typeof(prod), Tuple{Vector{Op}}}}}

julia> 2.3 * Op("X", 1) * Op("Y", 2) + Op("Rx", 2, (θ = π / 3,))
(2.3) * (X, 1) * (Y, 2) +
(1.0) * (Rx, 2, (θ = 1.0471975511965976,))

julia> typeof(2.3 * Op("X", 1) * Op("Y", 2) + Op("Rx", 2, (θ = π / 3,)))
Applied{typeof(sum), Tuple{Vector{Applied{typeof(*), Tuple{Float64, Applied{typeof(prod), Tuple{Vector{Op}}}}}}}}

julia> 3im * (2.3 * Op("X", 1) * Op("Y", 2) + Op("Rx", 2, (θ = π / 3,)))
(0.0 + 6.8999999999999995im) * (X, 1) * (Y, 2) +
(0.0 + 3.0im) * (Rx, 2, (θ = 1.0471975511965976,))

julia> Op("X", 1)'
adjoint(
(X, 1)
)
```
If you pay close attention to the third-to-last operation, you can see that there are a few automated conversions happening. The first operator is a scaled product of `Op`, while the second is just an `Op`, but when they are added they get converted to a common type which is a scaled product of `Op`. These rules are encoded in a type promotion and conversion system, just like Julia's automated type promotion and conversion of [numerical arithmetic](https://docs.julialang.org/en/v1/manual/conversion-and-promotion/#Promotion).

Currently I've implemented some simple conversions from one-site operators to ITensors, such as:
```julia
julia> s = siteinds("Qubit", 4);

julia> @show ITensor(Op("X", 1), s);
ITensor(Op("X", 1), s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 0.0  1.0
 1.0  0.0

julia> @show ITensor(exp(Op("X", 1)), s);
ITensor(exp(Op("X", 1)), s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 1.5430806348152435  1.1752011936438012
 1.1752011936438012  1.5430806348152435

julia> @show ITensor(2Op("X", 1), s);
ITensor(2 * Op("X", 1), s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 0.0  2.0
 2.0  0.0

julia> @show ITensor(2Op("X", 1) + Op("Y", 1), s);
ITensor(2 * Op("X", 1) + Op("Y", 1), s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{ComplexF64, Vector{ComplexF64}}
 2×2
 0.0 + 0.0im  2.0 - 1.0im
 2.0 + 1.0im  0.0 + 0.0im

julia> @show ITensor(Op("X", 1) + Op("iY", 1), s);
ITensor(Op("X", 1) + Op("iY", 1), s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{Float64, Vector{Float64}}
 2×2
 0.0  2.0
 0.0  0.0

julia> @show ITensor((Op("X", 1) + Op("iY", 1))', s);
ITensor((Op("X", 1) + Op("iY", 1))', s) = ITensor ord=2
Dim 1: (dim=2|id=816|"Qubit,Site,n=1")'
Dim 2: (dim=2|id=816|"Qubit,Site,n=1")
ITensors.NDTensors.Dense{Float64, Base.ReshapedArray{Float64, 1, LinearAlgebra.Adjoint{Float64, Matrix{Float64}}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}
 2×2
 0.0  0.0
 2.0  0.0
```
(Obviously leveraging the current `op` system to get the operator definitions.)

I still need to add the function for converting a sum of products of `Op` (currently aliased to `Ops.OpSum`, to replace `ITensors.OpSum`) to an MPO, which at this point is just a matter of data conversion to the format the AutoMPO system expects.

Future directions include using this format for circuit evolution and manipulation, for example taking the dagger of a circuit or exponentiating a circuit. Obviously a wide area would be using this format to automatically simplify circuits and local Hamiltonians. An interesting case would be defining `simplify` feature which could for example expand out a product of sums of operators, in order to represent `H^2`.

### CODE REVIEW

**Comment by mtfishman** [comment]
In the latest, I added support for converting from the new format `Ops.OpSum` to the current form `ITensors.OpSum`, and added conversion from `Ops.OpSum` to `MPO`. So this currently works:
```julia
using ITensors

function old_opsum(s)
  os = OpSum()
  for j in 1:(N - 1)
    os += "Sz", j, "Sz", j + 1
    os += 0.5, "S+", j, "S-", j + 1
    os += 0.5, "S-", j, "S+", j + 1
  end
  @show typeof(os)
  @show os
  return MPO(os, s)
end

function new_opsum(s)
  os = Ops.OpSum()
  for j in 1:(N - 1)
    os += "Sz", j, "Sz", j + 1
    os += 0.5, "S+", j, "S-", j + 1
    os += 0.5, "S-", j, "S+", j + 1
  end
  @show typeof(os)
  @show os
  return MPO(os, s)
end

N = 4
s = siteinds("S=1/2", N)
Hold = old_opsum(s)
Hnew = new_opsum(s)
@show prod(Hold) ≈ prod(Hnew)
```
Outputs:
```julia
typeof(os) = OpSum
os = OpSum:
  1.0 "Sz"(1) "Sz"(2) 
  0.5 "S+"(1) "S-"(2) 
  0.5 "S-"(1) "S+"(2) 
  1.0 "Sz"(2) "Sz"(3) 
  0.5 "S+"(2) "S-"(3) 
  0.5 "S-"(2) "S+"(3) 
  1.0 "Sz"(3) "Sz"(4) 
  0.5 "S+"(3) "S-"(4) 
  0.5 "S-"(3) "S+"(4) 

typeof(os) = ITensors.LazyApply.Applied{typeof(sum), Tuple{Vector{ITensors.LazyApply.Applied{typeof(*), Tuple{Float64, ITensors.LazyApply.Applied{typeof(prod), Tuple{Vector{Op}}}}}}}}
os = 1.0 Sz(1) * Sz(2) +
0.5 S+(1) * S-(2) +
0.5 S-(1) * S+(2) +
1.0 Sz(2) * Sz(3) +
0.5 S+(2) * S-(3) +
0.5 S-(2) * S+(3) +
1.0 Sz(3) * Sz(4) +
0.5 S+(3) * S-(4) +
0.5 S-(3) * S+(4)
prod(Hold) ≈ prod(Hnew) = true
```
So you can see that the new `Ops.OpSum` supports the same type of syntax as the current one. Internally, this is handled by automatically converting `Tuple`s to `Op` in operations like addition.

I think the only thing stopping us from using `Ops.OpSum` in the official interface is that it does not support the in-place addition syntax:
```julia
  os = OpSum()
  for j in 1:(N - 1)
    os .+= "Sz", j, "Sz", j + 1
    os .+= 0.5, "S+", j, "S-", j + 1
    os .+= 0.5, "S-", j, "S+", j + 1
  end
```
That shouldn't be hard to add.

**Comment by mtfishman** [comment]
Some "fancy" functionalities to have would be the following:
```julia
julia> (Op("X", 1) + Op("X", 2)) * (Op("Y", 1) + Op("Y", 2))
prod(
[X(1) +
X(2),
Y(1) +
Y(2)]
)

julia> expand((Op("X", 1) + Op("X", 2)) * (Op("Y", 1) + Op("Y", 2))) == Op("X", 1) * Op("Y", 1) + Op("X", 1) * Op("Y", 2) + Op("X", 2) * Op("Y", 1) + Op("X", 2) * Op("Y", 2)
ERROR: UndefVarError: expand not defined
Stacktrace:
 [1] top-level scope
   @ REPL[11]:1
```
which would output the expansion. This would allow getting the `Ops.OpSum` representation of `H^2` so it could be turned into an MPO. 

Another nice tool would be:
```julia
julia> exp(Op("X", 1) * Op("Y", 2) + Op("Y", 1) * Op("X", 1); alg=Trotter{2}(10))
```
which would output a product of exponentials  of the terms of the sum (specifically, an order 2 trotterization using `10` trotter steps). @GTorlai

**Comment by emstoudenmire** [comment]
Good to see this already so soon. I read through the examples carefully and see how a lot of it works, in terms of some parts being eager, promotion and conversion rules, and the rest.

Two questions I have:
* how are things like `sum` and `exp` stored? Are those `Symbol`s ?
* does the system evaluate cases like `Op("A",1) * Op("B",1)` where note that A and B are on the same site? Would it combine them into something like `Op("A*B",1)` automatically? If not, is this system the right place for that to happen or is that better left for inside of the functions that convert these inputs to MPOs or other targets?

**Comment by mtfishman** [comment]
> Good to see this already so soon. I read through the examples carefully and see how a lot of it works, in terms of some parts being eager, promotion and conversion rules, and the rest.
> 
> Two questions I have:
> 
>     * how are things like `sum` and `exp` stored? Are those `Symbol`s ?

The functions themselves are stored as a field in the `Applied` type. Julia `struct`s can store functions just like they can store any other object.

> 
>     * does the system evaluate cases like `Op("A",1) * Op("B",1)` where note that A and B are on the same site? Would it combine them into something like `Op("A*B",1)` automatically? If not, is this system the right place for that to happen or is that better left for inside of the functions that convert these inputs to MPOs or other targets?

I was picturing that `Op("A",1) * Op("B",1)` would be stored just like that, and then conversion functions like `MPO` or `ITensor` would take that format and multiply the operators together (which the `ITensor` conversion in this PR already does). So in this design I was picturing that `Op("A * B", 1)` would get converted immediately to `Op("A", 1) * Op("B", 1)`, analogous to how `Op(2.5, "A", 1)` gets converted to `2.5 * Op("A", 1)` in this design. We could imagine other convenient parsing tools, like converting `Op("exp(im * 0.1 * A)", 1)` to `exp(im * 0.1 * Op("A", 1))`, which we can think of as shorthands so that we don't have to expose people directly to the `Op` type too much as well as avoid making people define their own operators when they are just functionally dependent on simpler operators that are already defined.

**Comment by emstoudenmire** [comment]
I like both of those choices. I checked and storing Julia functions seems to have no size overhead whereas Symbols would have one, so it seems like a superior choice. (And it makes sure that what's stored are actual functions.) 

I guess for operations which aren't pre-defined functions, the `f` field has a parameterized type so it could be a Symbol or string or otherwise.

Sounds good about keeping the products separate. That's really the more "fundamental" thing and it's actually good now that you mention it to parse "A*B" into that as soon as possible, so that the string parsing logic isn't too deep in the rest of the code.

**Comment by mtfishman** [comment]
Also I forgot to mention that:
```julia
Op("X", 1, "Y", 2)
```
is just a shorthand that gets converted in the `Op` constructor directly to:
```julia
Op("X", 1) * Op("Y", 2)
```
so you can also use that syntax to make products of on-site operators.

**Comment by mtfishman** [comment]
In the latest I added an `expand` function which expands a product of sums of operators, for example:
```julia
julia> expand((Op("X", 1) + Op("X", 2)) * (Op("Y", 1) + Op("Y", 2)))
X(1) * Y(1) +
X(2) * Y(1) +
X(1) * Y(2) +
X(2) * Y(2)
```

This can be used for generating the square of a Hamiltonian, for example:
```julia
julia> function heisenberg(N)
         os = Ops.OpSum()
         for j in 1:(N - 1)
           os += "Sz", j, "Sz", j + 1
           os += 0.5, "S+", j, "S-", j + 1
           os += 0.5, "S-", j, "S+", j + 1
         end
         return os
       end

julia> H = heisenberg(4)
1.0 Sz(1) * Sz(2) +
0.5 S+(1) * S-(2) +
0.5 S-(1) * S+(2) +
1.0 Sz(2) * Sz(3) +
0.5 S+(2) * S-(3) +
0.5 S-(2) * S+(3) +
1.0 Sz(3) * Sz(4) +
0.5 S+(3) * S-(4) +
0.5 S-(3) * S+(4)

julia> H * H
prod(
[1.0 Sz(1) * Sz(2) +
0.5 S+(1) * S-(2) +
0.5 S-(1) * S+(2) +
1.0 Sz(2) * Sz(3) +
0.5 S+(2) * S-(3) +
0.5 S-(2) * S+(3) +
1.0 Sz(3) * Sz(4) +
0.5 S+(3) * S-(4) +
0.5 S-(3) * S+(4),
1.0 Sz(1) * Sz(2) +
0.5 S+(1) * S-(2) +
0.5 S-(1) * S+(2) +
1.0 Sz(2) * Sz(3) +
0.5 S+(2) * S-(3) +
0.5 S-(2) * S+(3) +
1.0 Sz(3) * Sz(4) +
0.5 S+(3) * S-(4) +
0.5 S-(3) * S+(4)]
)

julia> expand(H * H)
1.0 Sz(1) * Sz(2) * Sz(1) * Sz(2) +
0.5 S+(1) * S-(2) * Sz(1) * Sz(2) +
0.5 S-(1) * S+(2) * Sz(1) * Sz(2) +
1.0 Sz(2) * Sz(3) * Sz(1) * Sz(2) +
0.5 S+(2) * S-(3) * Sz(1) * Sz(2) +
0.5 S-(2) * S+(3) * Sz(1) * Sz(2) +
1.0 Sz(3) * Sz(4) * Sz(1) * Sz(2) +
[...]
```

**Comment by mtfishman** [comment]
A new feature in the latest commit is Trotter-Suzuki decomposition of a sum of operator expressions. For example:
```julia
using ITensors

function heisenberg(N)
  os = Sum{Op}()
  for j in 1:(N - 1)
    os += "Sz", j, "Sz", j + 1
    os += 0.5, "S+", j, "S-", j + 1
    os += 0.5, "S-", j, "S+", j + 1
  end
  return os
end

function main(N; nsteps, order)
  ℋ = heisenberg(N)
  s = siteinds("S=1/2", N)
  ψ₀ = MPS(s, n -> isodd(n) ? "↑" : "↓")
  t = 1.0
  𝒰 = exp(im * t * ℋ; alg=Trotter{order}(nsteps))
  U = Prod{ITensor}(𝒰, s)
  H = ITensor(ℋ, s)
  Uʳᵉᶠψ₀ = replaceprime(exp(im * t * H) * prod(ψ₀), 1 => 0)
  return norm(prod(U(ψ₀)) - Uʳᵉᶠψ₀)
end

@show main(4; nsteps=10, order=2)
@show main(4; nsteps=100, order=2)
@show main(4; nsteps=100, order=4)
```
returns:
```julia
main(4; nsteps = 10, order = 2) = 0.00035222091734113425
main(4; nsteps = 100, order = 2) = 3.5215911420683307e-6
main(4; nsteps = 100, order = 4) = 8.803965956665328e-7
```

**Comment by mtfishman** [comment]
I'm going to merge, since at first we can start using this in the background and we can work on the public interface later.

**Pull request merged**
