### PR TITLE
[ITensorGPU] Try newer version of Ubuntu for GPU CI tests

### PR DESCRIPTION
**Pull request by mtfishman**
# Description

Try fixing ITensorGPU CI tests.

See comments in #1035.

### CODE REVIEW

**Comment by mtfishman** [comment]
`nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04` also fails with `E: Unable to locate package libcutensor-dev`.

**Comment by dylex** [comment]
Yeah I was just looking at this -- it looks like nvidia has not released any libcutensor packages for ubuntu22.04... https://developer.nvidia.com/cutensor/downloads

**Comment by mtfishman** [comment]
That would explain it, that's unfortunate.

**Comment by dylex** [comment]
But you can just substitute `ubuntu20.04` on those instead (`nvidia/cuda:12.0.0-devel-ubuntu20.04`)

**Comment by mtfishman** [comment]
Using `nvidia/cuda:12.0.0-devel-ubuntu20.04` fixed the build issue but when the tests run I see the same error `This functionality is unavailabe as CUTENSOR is missing.` For some reason even though `libcutensor-dev` is being installed, `CUDA.jl` can't find it. Maybe it is some combination of how `CUDA.jl` is looking for the library (an automated process defined in https://github.com/JuliaGPU/CUDA.jl/blob/v3.13.1/deps/bindeps.jl) and something that changed in the upgrade to CUDA 12?

@kshyatt any suggestions?

**Comment by mtfishman** [comment]
Oh wait, I was still looking at the CI logs from a previous commit that was using `nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04`. Looks like `nvidia/cuda:12.0.0-devel-ubuntu20.04` ran successfully! Thanks for you help @dylex.

**Pull request merged**
