### PR TITLE
Increase tagset size to 16 characters

### PR DESCRIPTION
**Pull request by LinjianMa**
# Description

Increase tagset size to 16 characters, to handle the tagging of high dimensional tensor networks (e.g. 3D cubes, where we want taggings like "1.1.1↔2.1.1")

# How Has This Been Tested?

Additional tests have been added to check tagging with more than 8 characters.

Performance benchmark results as follows:
```
julia> @benchmark TagSet("abcdefgh,ijklmnop,qrstuvwx,ABCDEFGH")
BenchmarkTools.Trial: 10000 samples with 7 evaluations.
 Range (min … max):  4.155 μs … 258.125 μs  ┊ GC (min … max): 0.00% … 97.73%
 Time  (median):     4.292 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.580 μs ±   5.408 μs  ┊ GC (mean ± σ):  2.57% ±  2.18%

   █▃                                                          
  ▆██▆▄▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂ ▂
  4.15 μs         Histogram: frequency by time        7.87 μs <

 Memory estimate: 3.52 KiB, allocs estimate: 33.

julia> @benchmark TagSet("abcdefghijklm,nopqrstuvwxyz,ABCDEFGHIJKLM,NOPQRSTUVWXYZ")
BenchmarkTools.Trial: 10000 samples with 7 evaluations.
 Range (min … max):  4.720 μs … 248.964 μs  ┊ GC (min … max): 0.00% … 97.50%
 Time  (median):     4.851 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   4.991 μs ±   5.413 μs  ┊ GC (mean ± σ):  2.41% ±  2.18%

          ▄▆█ █▆▆ ▃▁                                           
  ▁▁▂▂▄▆█▆███████▆██▇▃▅▄▃▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▃
  4.72 μs         Histogram: frequency by time        5.33 μs <

 Memory estimate: 3.38 KiB, allocs estimate: 32.
```

# Checklist:

- [x] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by mtfishman** [comment]
Unfortunately it looks quite a bit slower than the previous version:
```julia
julia> using ITensors

(@v1.7) pkg> st ITensors
      Status `~/.julia/environments/v1.7/Project.toml`
  [9136182c] ITensors v0.3.0

julia> @benchmark TagSet("abcdefgh,ijklmnop,qrstuvwx,ABCDEFGH")
BenchmarkTools.Trial: 10000 samples with 651 evaluations.
 Range (min … max):  189.919 ns …   5.943 μs  ┊ GC (min … max): 0.00% … 96.35%
 Time  (median):     201.169 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   226.338 ns ± 314.799 ns  ┊ GC (mean ± σ):  8.77% ±  6.05%

   ▁▄▇▅█▆▄▃▂▁▁▁▂▂▁                                              ▁
  ▇█████████████████▇▇▇▇▇▇▇▇▆▆▆▆▆▆▅▆▆▆▅▅▆█▇▇██▆▆▅▅▅▄▄▄▆▅▃▄▅▄▂▅▃ █
  190 ns        Histogram: log(frequency) by time        313 ns <

 Memory estimate: 288 bytes, allocs estimate: 6.
```

**Comment by mtfishman** [comment]
Here are some more benchmarks:
```julia
using ITensors

ts_string = "abcdefgh,ijklmnop,qrstuvwx,ABCDEFGH"
ts = TagSet(ts_string)
i = Index(2, ts_string)
A = randomITensor(i', i)
bench_tagset = @benchmark TagSet($ts_string)
bench_tagset_compare = @benchmark $ts == $ts
bench_sum = @benchmark $A + $A
bench_contract = @benchmark $(A') * $A

display(bench_tagset)
display(bench_tagset_compare)
display(bench_sum)
display(bench_contract)
```

This branch gives:
```julia
BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  2.917 μs … 312.574 μs  ┊ GC (min … max): 0.00% … 98.56%
 Time  (median):     3.023 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.349 μs ±   7.291 μs  ┊ GC (mean ± σ):  5.31% ±  2.42%

  ▇██▆▄▂   ▁▂▂▃▃▃▃▂▃▂▂▁                                       ▂
  ███████▇▇█████████████▇▇▇▆▇▇▆▇▆▅▇█▇▆▆▅▄▆▆▆▄▄▅▄▃▇▇▅▃▄▄▁▄▅▄▅▄ █
  2.92 μs      Histogram: log(frequency) by time      5.55 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 32.
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  3.055 ns … 33.237 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.739 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.542 ns ±  1.040 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▄                                                     ▅█  
  ▄▄█▆▁▂▂▂▂▂▁▁▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▄▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▂▅██ ▃
  3.06 ns        Histogram: frequency by time        3.76 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.173 μs … 234.421 μs  ┊ GC (min … max): 0.00% … 98.91%
 Time  (median):     1.238 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.500 μs ±   5.378 μs  ┊ GC (mean ± σ):  8.72% ±  2.42%

  ▄██▇▆▅▄▃▂▂▁                   ▂▂▂▁▂▃▃▃▂▂▂▂▁▁                ▂
  ███████████▇▇▇▆▆▅▅▅▁▄▅▄▅▄▄▄▄▅█████████████████▇▆▆▅▅▆▄▇▆▆▅▇▇ █
  1.17 μs      Histogram: log(frequency) by time      2.41 μs <

 Memory estimate: 2.80 KiB, allocs estimate: 22.
BenchmarkTools.Trial: 10000 samples with 23 evaluations.
 Range (min … max):  954.348 ns … 77.236 μs  ┊ GC (min … max): 0.00% … 97.86%
 Time  (median):     987.261 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.128 μs ±  2.457 μs  ┊ GC (mean ± σ):  7.50% ±  3.40%

  ▅██▇▆▅▄▂                                 ▁▁▁▁▁▁▁▁ ▁          ▂
  █████████▇▇█▇▆▅▄▅▄▄▁▃▃▃▁▁▃▃▁▁▁▁▁▁▁▁▄▅▆▇███████████████▇▆▇▆▆▇ █
  954 ns        Histogram: log(frequency) by time      1.74 μs <

 Memory estimate: 2.39 KiB, allocs estimate: 14.
```
while ITensors 0.3.6 gives:
```julia
BenchmarkTools.Trial: 10000 samples with 690 evaluations.
 Range (min … max):  182.561 ns …  13.220 μs  ┊ GC (min … max): 0.00% … 97.78%
 Time  (median):     191.975 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   216.642 ns ± 335.425 ns  ┊ GC (mean ± σ):  8.09% ±  5.35%

  ▂▇▇██▇▅▃▂                 ▁                                   ▂
  ██████████▇▇▇▇███▇█▇▇▇▇███████▇▇▇▇▆▇▇▇▆▇▇▇▇▆▆▅▄▆▆▇▅▆▅▅▅▆▅▅▆▄▆ █
  183 ns        Histogram: log(frequency) by time        330 ns <

 Memory estimate: 208 bytes, allocs estimate: 5.
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  3.455 ns … 30.476 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.748 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.743 ns ±  0.752 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▁▂▁▁▂▂▂▂▂▂▁▂▂▁▂▂▁▂▂▂▂▂▂▂▁                       ▃▄▄▄███▇ ▂
  ████████████████████████████▇▁▁▁▁▃▁▁▃▃▁▁▃▁▁▁▁▁▁▁▅█████████ █
  3.46 ns      Histogram: log(frequency) by time     3.76 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.018 μs … 259.859 μs  ┊ GC (min … max): 0.00% … 99.08%
 Time  (median):     1.067 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.275 μs ±   5.106 μs  ┊ GC (mean ± σ):  7.97% ±  1.98%

  ▄██▇▅▄▂▂▁▁           ▃▃▃▂▂▁▂▃▃▃▁▁▁▁▁▁                       ▂
  ███████████▇▇▆▅▂▄▃▄▅██████████████████▇█▇▆▆▅▄▄▄▄▄▅▆▆▅▅▅▅▅▄▅ █
  1.02 μs      Histogram: log(frequency) by time      1.98 μs <

 Memory estimate: 1.95 KiB, allocs estimate: 22.
BenchmarkTools.Trial: 10000 samples with 36 evaluations.
 Range (min … max):  902.778 ns … 57.635 μs  ┊ GC (min … max): 0.00% … 98.15%
 Time  (median):     925.611 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.035 μs ±  1.949 μs  ┊ GC (mean ± σ):  6.76% ±  3.53%

  ▄██▇▅▄▃▂▁                                 ▁▁▁▁▁              ▂
  ████████████▇▇▆▄▅▄▅▃▃▁▁▃▃▃▃▄▅▅▅▇▇▇███▇▇█████████▇▆▆▆▆▆▆▇▇▆▆▇ █
  903 ns        Histogram: log(frequency) by time      1.47 μs <

 Memory estimate: 1.69 KiB, allocs estimate: 14.
```
The timing for very small tensor contraction and addition barely changed so I think this is ok to merge and we can always circle back to the TagSet constructor later, I'm sure that could be optimized more independent of this PR.

**Comment by mtfishman** [comment]
For completeness, here are benchmarks for in-place addition and contraction.
```julia
using ITensors

ts_string = "abcdefgh,ijklmnop,qrstuvwx,ABCDEFGH"
ts = TagSet(ts_string)
i = Index(2, ts_string)
A = randomITensor(i', i)
B = randomITensor(i', i)
C = randomITensor(i'', i)

bench_tagset = @benchmark TagSet($ts_string)
bench_tagset_compare = @benchmark $ts == $ts
bench_sum = @benchmark $B .= $B .+ $A
bench_contract = @benchmark $C .= $(A') .* $A

display(bench_tagset)
display(bench_tagset_compare)
display(bench_sum)
display(bench_contract)
```
On this branch:
```julia
BenchmarkTools.Trial: 10000 samples with 9 evaluations.
 Range (min … max):  2.966 μs … 257.994 μs  ┊ GC (min … max): 0.00% … 98.51%
 Time  (median):     3.028 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.329 μs ±   6.170 μs  ┊ GC (mean ± σ):  4.51% ±  2.41%

  ▅█▇▅▄▁            ▁▁ ▁▁▁▁▁▁                                 ▁
  ██████▇▇▆▇▆▇▆▆▇▇▇██████████████▇██▇▇▇▇▇▆▇▆▆▅▅▅▅▆▇▇▅▅▅▄▃▃▃▄▄ █
  2.97 μs      Histogram: log(frequency) by time      4.77 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 32.
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  3.048 ns … 37.081 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.731 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.670 ns ±  1.121 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                                                     █▄       
  ▃▃▅▃▁▂▂▂▂▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▆▃▁▁▁▂▂▂▂▂▁▂▂▂▂▃██▆▂▂▂▂ ▂
  3.05 ns        Histogram: frequency by time        3.82 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
BenchmarkTools.Trial: 10000 samples with 39 evaluations.
 Range (min … max):  898.718 ns … 102.915 μs  ┊ GC (min … max): 0.00% … 98.54%
 Time  (median):     918.897 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):     1.037 μs ±   2.505 μs  ┊ GC (mean ± σ):  7.57% ±  3.11%

  ▅█▇▅▅▄▄▃▃▂▁           ▁▁▂▂▂▂▁▁                                ▂
  ████████████▇▆▅▄▄▄▁▁▄██████████▇▇▆▆▆▇█▇▇▇▆▇▆▇▅▆▄▄▄▄▄▄▅▄▄▄▄▄▁▃ █
  899 ns        Histogram: log(frequency) by time       1.46 μs <

 Memory estimate: 1.22 KiB, allocs estimate: 14.
BenchmarkTools.Trial: 10000 samples with 188 evaluations.
 Range (min … max):  543.771 ns …  11.055 μs  ┊ GC (min … max): 0.00% … 93.80%
 Time  (median):     551.282 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   615.979 ns ± 679.961 ns  ┊ GC (mean ± σ):  7.90% ±  6.75%

  ▇█▅▄▃▁                                                        ▁
  ███████▅▅▅▄▂▅█▇▇▅▅▆▆▅▄▅▃▄▄▂▄▄▅▇▆▇▆▅▅▄▅▅▆▅▄▆▅▅▆▅▄▅▅▅▆▆▃▅▇█▆▅▅▇ █
  544 ns        Histogram: log(frequency) by time        890 ns <

 Memory estimate: 1.25 KiB, allocs estimate: 10.
```
and on ITensors 0.3.7:
```julia
BenchmarkTools.Trial: 10000 samples with 709 evaluations.
 Range (min … max):  177.539 ns …   8.049 μs  ┊ GC (min … max): 0.00% … 97.42%
 Time  (median):     189.477 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   209.002 ns ± 271.855 ns  ┊ GC (mean ± σ):  7.23% ±  5.41%

   ▁▅▇▆██▇▇▆▅▃▂▂▁        ▁                                      ▂
  ▄███████████████▇███▇▅▇█▇▇▇▇▇▇█▇▇██▇▇▇▆▅▆▅▅▆▅▄▃▅▇▇▇▆▆▆▆▅▄▅▄▄▃ █
  178 ns        Histogram: log(frequency) by time        290 ns <

 Memory estimate: 208 bytes, allocs estimate: 5.
BenchmarkTools.Trial: 10000 samples with 1000 evaluations.
 Range (min … max):  3.287 ns … 9.272 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     3.732 ns             ┊ GC (median):    0.00%
 Time  (mean ± σ):   3.738 ns ± 0.099 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                                                      ▆█▁▅▃  
  ▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▂▁▁▂▁▂▁▁▁▂▂▂▁▂▁▁▁▁▁▁▁▁▁▁▁▁▇█████ ▃
  3.29 ns        Histogram: frequency by time       3.76 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
BenchmarkTools.Trial: 10000 samples with 80 evaluations.
 Range (min … max):  826.925 ns … 42.125 μs  ┊ GC (min … max): 0.00% … 97.49%
 Time  (median):     866.913 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   946.613 ns ±  1.446 μs  ┊ GC (mean ± σ):  6.09% ±  3.89%

  ▄▆▆██▇▇▇▆▅▃▂▁▁       ▁▁                                      ▂
  ██████████████▇▇▇████████████▇▆████▇█▆▇▅▇▆▆▅▅▅▃▃▅▂▄▂▂▄▄▅▅▂▄▅ █
  827 ns        Histogram: log(frequency) by time      1.29 μs <

 Memory estimate: 960 bytes, allocs estimate: 14.
BenchmarkTools.Trial: 10000 samples with 189 evaluations.
 Range (min … max):  548.566 ns …  22.841 μs  ┊ GC (min … max): 0.00% … 95.35%
 Time  (median):     586.524 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   642.161 ns ± 711.318 ns  ┊ GC (mean ± σ):  6.85% ±  5.95%

     ▃▅▅█▇▅▆▄▂▂                                                 ▂
  ▄▇▇███████████▆▅▆▇▇▆▅▅▆▆▆▆▇▄▄▅▄▅▄▄▄▅▆▅▆▇▇▆▆▇▇▆▆▅▅▄▄▅▆▅▄▅▅▅▄▄▅ █
  549 ns        Histogram: log(frequency) by time        878 ns <

 Memory estimate: 992 bytes, allocs estimate: 10.
```
so even for faster in-place operations it is not really noticeable.

**Comment by LinjianMa** [comment]
@mtfishman thanks for helping with benchmarking it!

**Comment by emstoudenmire** [comment]
Great. Just to understand, what was changed between the earlier timing that showed it was slower to these newer timings? One other question is whether this change will make a significant impact on the memory footprint of smallish ITensors (I doubt it but just worth thinking about).

**Comment by LinjianMa** [comment]
> Great. Just to understand, what was changed between the earlier timing that showed it was slower to these newer timings? One other question is whether this change will make a significant impact on the memory footprint of smallish ITensors (I doubt it but just worth thinking about).

I think the previous benchmark only tested the Tagset constructor, where the current version is slower (4.292 μs vs 201.169 ns). This is still the case in Matt's recent benchmark. But for other operations (tagset_compare, sum, contract), it seems the results are comparable.

**Comment by mtfishman** [comment]
Linjian's summary is correct. I reorganized my previous comments to make the comparisons easier to see.

I did some profiling and it turns out the fix for the performance regression was very simple (just using `Val(N)` in a tuple constructor instead of just `N` to make the constructor type-stable). I'm not sure why this change was required, before I think constant propagation was automatically making the tuple constructor type stable but maybe it can't do that with longer tuples (since now the tuples are of length 16). I added a new benchmark for the TagSet constructor using the latest commit (labeled under "This branch (after optimization)". You can see that the time went back to the previous time, and the allocations went down a bit!

Anyway, at this point I don't think there is any reason not to merge this.

**Comment by emstoudenmire** [comment]
I'm good with merging this. It does seem very useful, as we've had to limit some tag names like for site types in the past, leading to awkward names. And the case of tagging for 3D or other advanced applications makes a lot of sense.

**Pull request merged**
