### PR TITLE
WIP: svd of QN ITensor

### PR DESCRIPTION
**Pull request by mtfishman**
Here is a working version of svding QN ITensors. In the process I found some bugs in the QN combiner code, so I also rewrote that and it seems to be better now.

~~Right now the svd for QN ITensors doesn't include truncation, I will add that in this pull request as well.~~

I just added support for truncation.

### CODE REVIEW

**Comment by mtfishman** [comment]
I'm not sure what the test failure is (I don't see any issues locally). Otherwise this is good to go!

**Comment by emstoudenmire** [comment]
Looking at the test output, it seems there's an extra "end" keyword around line 822 of itensor_blocksparse.jl. I think I had a similar issue when running it on my machine on a different branch I'm working on.

**Comment by emstoudenmire** [comment]
Great progress on the SVD! We are nearly at feature parity with the C++ version!

**Comment by mtfishman** [comment]
I tried finding a mismatched `end` keyword but couldn't find one. Strangely, it is not caught for me locally (usually the julia-vim plugin will point out mismatched `end` keywords) and is only failing on travis-ci/pr and not travis-ci/push (I don't know what the difference between them is). I wonder if it is an issue with travis-ci/pr?

I made an MPO by hand for the 1D Heisenberg model, and with the latest commits I got DMRG running with QNs (although it is pretty slow right now). Here are results for the S=1/2 Heisenberg model with Sz conservation for 50 sites:

C++ ITensor (single threaded):
```
    vN Entropy at center bond b=25 = 0.894180338607
    Eigs at center bond b=25: 0.4795 0.4795 0.0158 0.0158 0.0022 0.0022 0.0022 0.0022 
    Largest link dim during sweep 5/5 was 70
    Largest truncation error: 7.96065e-11
    Energy after sweep 5/5 is -21.972110267847
    Sweep 5/5 CPU time = 0.397s (Wall time = 0.403s)

Ground State Energy = -21.9721102678
```
and for this branch:
```
After sweep 1 energy=-21.813431523642 maxlinkdim=4 time=0.247
After sweep 2 energy=-21.960017595421 maxlinkdim=16 time=1.154
After sweep 3 energy=-21.972020200796 maxlinkdim=50 time=8.943
After sweep 4 energy=-21.972110118684 maxlinkdim=68 time=24.043
After sweep 5 energy=-21.972110267767 maxlinkdim=71 time=27.028
Final energy = -21.972110267767
```
I included this in the `examples/dmrg/qns` directory. Clearly there are some performance issues, but I can do some profiling and work on that in another PR (in general I haven't done much investigation of the performance of the block sparse code, so I am not surprised there is room for improvement).

I think this is ready to go!

**Comment by mtfishman** [comment]
The major performance issue was the same one Ori pointed out in #184. After the latest commit, I see:
```
After sweep 1 energy=-21.813431523642 maxlinkdim=4 time=0.399
After sweep 2 energy=-21.960017595421 maxlinkdim=16 time=0.815
After sweep 3 energy=-21.972020200796 maxlinkdim=50 time=1.386
After sweep 4 energy=-21.972110118684 maxlinkdim=68 time=1.879
After sweep 5 energy=-21.972110267767 maxlinkdim=71 time=1.987
Final energy = -21.972110267767
```
so much better. I'll merge this and work on closing the performance gap more in later PRs.

**Comment by emstoudenmire** [comment]
This is big! Congrats Matt. Great to see you are also already finding the key bottlenecks.

**Pull request merged**
