### PR TITLE
[ITensors] `OpSum` to `MPO` conversion type stability

### PR DESCRIPTION
**Pull request by mtfishman**
# Description

Supersedes #1183, with some additional code reorganization and cleanup.

### CODE REVIEW

**Comment by mtfishman** [comment]
[test ITensors mps]

**Comment by mtfishman** [comment]
[test ITensors mps]

**Comment by terasakisatoshi** [comment]
Hi @mtfishman, thank you for feedback in my PR in #1183

Here is what I did on your `ITensors_opsum_type_stability` branch  https://github.com/ITensor/ITensors.jl/pull/1184/commits/8edfa07b07be81c881965fe570566f0647364020

```console
ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ git show --format='%h' --no-patch
bbecc8b6c

ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ cat mpo_bench.jl                                                 
using ITensors

include("paulis.jl")
conserve_qns = false
@info "conserve_qns" conserve_qns
sites = siteinds("Qubit", N; conserve_qns)
os = ITensors.OpSum()

for p in paulis
  coeff = rand()
  global os
  os += ITensors.Ops.op_term((coeff, p...))
end

@time MPO(os, sites)
@time MPO(os, sites)
@time MPO(os, sites)

ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ julia mpo_bench.jl 
┌ Info: conserve_qns
└   conserve_qns = false
 28.424578 seconds (199.12 M allocations: 10.196 GiB, 6.61% gc time, 46.17% compilation time)
 14.791576 seconds (168.27 M allocations: 8.186 GiB, 7.82% gc time)
 15.261162 seconds (168.27 M allocations: 8.186 GiB, 7.64% gc time)
```

My pull request #1183 is getting better results:

```
ITensors.jl on  improve-type-stability-of-svdMPO [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 took 2m51s 
❯ julia mpo_bench.jl 
┌ Info: conserve_qns
└   conserve_qns = false
 22.455729 seconds (31.28 M allocations: 7.094 GiB, 5.38% gc time, 55.11% compilation time)
 10.126017 seconds (3.96 M allocations: 5.315 GiB, 8.45% gc time)
 10.914117 seconds (3.96 M allocations: 5.315 GiB, 6.65% gc time)
```

`versioninfo()` outputs the following information:

```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 16 × Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, skylake)
  Threads: 1 on 16 virtual cores
Environment:
  JULIA_PROJECT = @.
  JULIA_EDITOR = code
```

Unfortunately, I get an error when `conserve_qns` is `true`:

```console
ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ git show --format='%h' --no-patch
bbecc8b6c

ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ cat mpo_bench.jl                 
using ITensors

include("paulis.jl")
conserve_qns = true
@info "conserve_qns" conserve_qns
sites = siteinds("Qubit", N; conserve_qns)
os = ITensors.OpSum()

for p in paulis
  coeff = rand()
  global os
  os += ITensors.Ops.op_term((coeff, p...))
end

@time MPO(os, sites)
@time MPO(os, sites)
@time MPO(os, sites)

ITensors.jl on  ITensors_opsum_type_stability [?] is 📦 v0.3.41 via ஃ v1.9.3 via 🐍 v3.10.8 
❯ julia mpo_bench.jl               
┌ Info: conserve_qns
└   conserve_qns = true
ERROR: LoadError: BoundsError: attempt to access 1×1 Matrix{Float64} at index [1, 2]
Stacktrace:
 [1] getindex(::Matrix{Float64}, ::Int64, ::Int64)
   @ Base ./essentials.jl:14
 [2] svd_mpo(coefficient_type::Type, os::Sum{Scaled{ComplexF64, Prod{Op}}}, sites::Vector{Index{Vector{Pair{QN, Int64}}}}; mindim::Int64, maxdim::Int64, cutoff::Float64)
   @ ITensors ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_qn.jl:134
 [3] svd_mpo
   @ ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_qn.jl:1 [inlined]
 [4] mpo_specified_coefficient_type(coefficient_type::Type, os::Sum{Scaled{ComplexF64, Prod{Op}}}, sites::Vector{Index{Vector{Pair{QN, Int64}}}}; splitblocks::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ITensors ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_generic.jl:311
 [5] mpo_specified_coefficient_type
   @ ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_generic.jl:304 [inlined]
 [6] MPO(os::Sum{Scaled{ComplexF64, Prod{Op}}}, sites::Vector{Index{Vector{Pair{QN, Int64}}}}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ITensors ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_generic.jl:301
 [7] MPO(os::Sum{Scaled{ComplexF64, Prod{Op}}}, sites::Vector{Index{Vector{Pair{QN, Int64}}}})
   @ ITensors ~/work/fork/ITensors.jl/src/physics/autompo/opsum_to_mpo_generic.jl:300
 [8] top-level scope
   @ ./timing.jl:273
in expression starting at /Users/terasakisatoshi/work/fork/ITensors.jl/mpo_bench.jl:15
```

**Comment by terasakisatoshi** [comment]
The code below is a MWE that reproduces the error above.

```julia
using ITensors

N=4
paulis = [
    ["Z",1],
    ["Z",1,"Z",4],
    ["Z",2,"Z",3],
]

conserve_qns = true
@info "conserve_qns" conserve_qns
sites = siteinds("Qubit", N; conserve_qns)
os = ITensors.OpSum()

for p in paulis
  coeff = rand()
  global os
  os += ITensors.Ops.op_term((coeff, p...))
end

@time MPO(os, sites)
```

**Comment by mtfishman** [comment]
Thanks for checking @terasakisatoshi. I also noticed that bug. Let's just go ahead with your more minimal PR for now. I'll make some comments over there.

**Pull request closed without merging**
