### PR TITLE
`contract` functionality in AD

### PR DESCRIPTION
**Pull request by hjkqubit**
# Description

Added `contract` function for `MPO` on `MPS` into mpo.jl file for AD.

`using JuliaFormatter; format(".")` made some edits on other unintended files.

EDIT: added tests to `test_chainrules.jl`

# Checklist:

- [ ] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that verify the behavior of the changes I made.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by mtfishman** [comment]
Thanks @hjkqubit! Could you add a test for this? You could write something similar to the ones for contracting MPOs with each other (https://github.com/ITensor/ITensors.jl/blob/c2e18d24e336dc2c50281017c71d1b678e316e7e/test/ITensorChainRules/test_chainrules.jl#L710).

**Comment by hjkqubit** [comment]
No worries @mtfishman! Yep, I just did -- I ran `julia runtests.jl` inside the `ITensors.jl/test/ITensorChainRules/` directory on my local machine to make sure.

**Comment by mtfishman** [comment]
Thanks for the tests @hjkqubit. Could you run the formatter again?

**Comment by hjkqubit** [comment]
I just ran the formatter (after syncing my forked repository), it returned `true`, and it didn't change any of my files-- is there anything I need to push onto my forked repository?

**Comment by mtfishman** [comment]
Maybe you need to update your local version of `JuliaFormatter.jl`?

**Comment by mtfishman** [comment]
Could you manually fix the lines according to the suggestions on: https://github.com/ITensor/ITensors.jl/pull/1025/files?

**Comment by hjkqubit** [comment]
@mtfishman Sorry for the delay -- I made the manual fixes

**Pull request merged**
