### PR TITLE
[ITensors] test sample MPO

### PR DESCRIPTION
**Pull request by kshyatt**
# Description

Added a missing test for `sample`-ing an MPO, which wasn't covered.

# How Has This Been Tested?

Tests passed locally

# Checklist:

- [x] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that verify the behavior of the changes I made.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by emstoudenmire** [comment]
Thanks!

**Comment by mtfishman** [comment]
[mps]

**Comment by kshyatt** [comment]
It's running here: https://github.com/ITensor/ITensors.jl/actions/runs/4388790545

**Comment by kshyatt** [comment]
MPS tests passed 😎

**Comment by mtfishman** [comment]
Thanks! Also glad to see the comment triggered testing put to good use and working (though I need to figure out how to get it to report the results in a comment to the PR, maybe with an `ITensorBot`...).

**Pull request merged**
