### PR TITLE
typo in subtraction of 2 dense tensors on GPU

### PR DESCRIPTION
**Pull request by kbidzhiev**
# Description
issue[#1023](https://github.com/ITensor/ITensors.jl/issues/1023)

```julia
function Base.:-(B::CuDenseTensor, A::CuDenseTensor)
```
the code should return B-A, instead it returns A-B

### CODE REVIEW

**Comment by mtfishman** [comment]
Thanks, could you please add a test?

**Comment by kbidzhiev** [comment]
I've added test.

Moreover I have couple of questions.
Why it's necessary to copy results in the file ITensorGPU/src/tensor/cudense.jl

```julia
function Base.:-(B::CuDenseTensor, A::CuDenseTensor)
...
  copyto!(data(store(B)), vec(C))
  return B
```

and the same for 
```julia
function Base.:-(A::CuDense, Ais::IndexSet, B::CuDense, Bis::IndexSet)
...
  copyto!(data(B), vec(C))
  return C
```

for which reason two functions are not similar ?

**Comment by mtfishman** [comment]
Thanks for the PR and tests!

Could you raise a separate issue about that? The second definition should probably be removed.

**Comment by mtfishman** [comment]
Also, could you run the formatter to format your code?

**Comment by kbidzhiev** [comment]
> Also, could you run the formatter to format your code?

Done :)

**Pull request merged**
