### PR TITLE
Add normalize! to TEBD Tutorial

### PR DESCRIPTION
**Pull request by emstoudenmire**
Norm should be kept at 1.0 for real-time TEBD Tutorial in the docs.

### CODE REVIEW

**Comment by mtfishman** [comment]
It would be good to have a flag `normalize` in `apply` that turned this on and off internally.

**Comment by emstoudenmire** [comment]
Yes agreed. And I would argue that the default should be off, since that way the literal meaning is to apply the gates to the state. For TVDP I was kind of debating about a similar thing: should we primarily think of it as "applying" exp(H t) to the state and returning that, or as a "time evolution of quantum states" algorithm where one prefers the state to be normalized. I guess logically the first one, but then it's a little frustrating that for the application it will be used the most for, a best practice is to pass a keyword arg `normalize=true` every time.

**Comment by mtfishman** [comment]
Yeah, I prefer taking the more literal version by default (so `normalize=false` by default). In general people will use unitary evolution anyway, in which case using `normalize=true` wouldn't be so important anyway (and then the norm of the resulting state can give some idea for the truncation/fidelity loss).

**Comment by emstoudenmire** [comment]
Ok so then we're agreed about that. I just switched the default to be not to normalize in TDVP, and we can also nicely add that keyword arg to `apply` without it changing any default behavior that way too.

**Pull request merged**
