### PR TITLE
Make OpName use Symbol instead of SmallString for longer operator names

### LINKED ISSUE #550: Use Symbol instead of SmallString in OpName
If we switch OpName to use a Symbol instead of a SmallString, we could use longer operator names.

### PR DESCRIPTION
**Pull request by mtfishman**
Closes #550.

### CODE REVIEW

**Comment by mtfishman** [comment]
@emstoudenmire, just 2 lines of code needed. I don't really see any disadvantage. The interface doesn't change, since it is still overloaded with the same notation.

**Comment by emstoudenmire** [comment]
Looks good! I guess the only possible downside I can think of then is performance, though it could be that this approach is actually faster.

**Comment by mtfishman** [comment]
With this design, making an OpName from a String is very fast:
```julia
julia> using ITensors

julia> @btime OpName($(Ref("abcdefgh"))[])
  104.089 ns (0 allocations: 0 bytes)
OpName{:abcdefgh}()

julia> @btime OpName($(Ref("abcdefghijklmnopqr"))[])
  102.066 ns (0 allocations: 0 bytes)
OpName{:abcdefghijklmnopqr}()
```
(The use of `Ref` stops the compiler from optimizing away the operation, see here: https://github.com/JuliaCI/BenchmarkTools.jl/blob/master/doc/manual.md#understanding-compiler-optimizations).

On v0.1.33 the time was:
```julia
julia> @btime OpName($(Ref("abcdefgh"))[])
  134.797 ns (3 allocations: 96 bytes)
OpName{abcdefgh}()
```
so a bit slower because of the String to SmallString conversion:
```julia
julia> @btime ITensors.SmallString($(Ref("abcdefgh"))[])
  27.446 ns (1 allocation: 32 bytes)
abcdefgh
```

**Comment by mtfishman** [comment]
I'll merge this once I see tests passing.

**Comment by emstoudenmire** [comment]
Great. Of course we have the benchmarks above but good to see that OpName-specific micro benchmark. I'm confident it's a good change now.

**Pull request merged**
