### PR TITLE
Added errMPOProd

### PR DESCRIPTION
**Pull request by alvarorga**
Hi,
This addresses issues #60 and #45.

I first added a new inner method `inner(B::MPO, y::MPS, A::MPO, x::MPS)` to compute `<By|A|x>`. Then I used that method to define the distance in `errMPOProd(y::MPS, A::MPO, x::MPS)` as `real(inner(y, y) - 2*inner(y, A, x) + inner(A, x, A, x))`.

You may find in `inner` that my way of swapping the prime levels is not very elegant (I use a temporal 3 level prime). If you find a better approach I'll be happy to change it.

### CODE REVIEW

**Comment by alvarorga** [comment]
Hi again, two things:

1. When I made the tests for `inner` I reproduced the same kind of test as was done for `inner(y::MPS, A::MPO, x::MPS)` ([here](https://github.com/ITensor/ITensors.jl/blob/master/test/test_mpo.jl#L34)), which is very similar to the [code in the method](https://github.com/ITensor/ITensors.jl/blob/master/src/mps/mpo.jl#L213). Maybe the tests for `inner` would benefit if the actual computation was manually done, like
```julia
@testset "inner <y|A|x>" begin
    L = 5
    sites = spinHalfSites(L)
    
    x = randomMPS(sites)
    y = randomMPS(sites)
    A = randomMPO(sites)
    
    O = 1.
    for j ∈ eachindex(x)
        xj = reshape(Array(x[j]), 2)
        yj = reshape(Array(y[j]), 2)
        Aj = reshape(Array(A[j]), 2, 2)
        O *= (yj'*transpose(Aj)*xj)[]
    end

    @test O ≈ inner(y, A, x)

    badSites = spinHalfSites(L+2)
    badx = randomMPS(badSites)
    @test_throws DimensionMismatch inner(y, A, badx)
end

@testset "inner <By|A|x>" begin
    L = 5
    sites = spinHalfSites(L)
    
    x = randomMPS(sites)
    y = randomMPS(sites)
    A = randomMPO(sites)
    B = randomMPO(sites)
    
    O = 1.
    for j ∈ eachindex(x)
        xj = reshape(Array(x[j]), 2)
        yj = reshape(Array(y[j]), 2)
        Aj = reshape(Array(A[j]), 2, 2)
        Bj = reshape(Array(B[j]), 2, 2)
        O *= ((transpose(Bj)*yj)'*transpose(Aj)*xj)[]
    end

    @test O ≈ inner(B, y, A, x)

    badSites = spinHalfSites(L+2)
    badx = randomMPS(badSites)
    @test_throws DimensionMismatch inner(B, y, A, badx)
end
```

2. Now that the `inner` function is available, maybe it is a good idea to write functions for the variance / standard deviation of a measurement.

**Comment by emstoudenmire** [comment]
Thanks for the high quality PR! 

This is already good enough to pull, but if you don't mind here are a couple changes right off the bat that would make this better:
1. could you please rename the function to `errorMPOProd` ? The reason is just that it is the name we have used in the C++ version (the bug / feature request may have misleadingly said otherwise)
2. could you also refactor the algorithm in `errorMPOProd` to reproduce the following code from our C++ version (also visible here: https://github.com/ITensor/ITensor/blob/v3/itensor/mps/mpo.cc). The main change is that the error gets normalized by <x|A^dag A|x> so that it becomes independent of the norm of A, I believe. (Someone earlier sent us a pull request in our C++ version making this change because they had found cases where a simpler definition of the error could be misleadingly large or small.) Here's the code --- note that innerC in C++ can just be replaced with inner in Julia since in Julia inner can return a real or complex number from the same function:

```
Real
errorMPOProd(MPS const& y,
             MPO const& A, 
             MPS const& x)
    {
    auto err = real(innerC(y,y));
    err += -2.*real(innerC(y,A,x));
    err /= real(innerC(A,x,A,x));
    err = std::sqrt(std::abs(1.0+err));
    return err;
    }
```

**Comment by alvarorga** [comment]
Great! I renamed the function to `errorMPOProd` and divided by the norm of `A|x>`. I also added to the `inner` methods test the manual contractions I described earlier.

**Comment by emstoudenmire** [comment]
Great - one last thing is, in the test for errorMPOProd, could you add a test that does applyMPO on some MPS and MPO and uses errorMPOProd to make sure the error is close to zero? Thanks!

**Comment by alvarorga** [comment]
Sure, I just added it to the test of `errorMPOProd`. One thing that confused me a little is that I have to use `applyMPO` with `maxdim=1`, otherwise I don't always get a 0 distance. I don't know whether that behavior is expected. See this little code:
```julia
using Test, ITensors

L = 7
sites = spinHalfSites(L)
    
x = randomMPS(sites)
A = randomMPO(sites)
Ax = applyMPO(A, x)
B = applyMPO(A, x, maxdim=1)
    
@test inner(x, A, x) ≈ inner(x, B) # Always passes.
@test inner(x, A, x) ≈ inner(x, Ax) # Mostly fails.
```
Sometimes it passes and sometimes it doesn't. The relative distance between `inner(x, A, x)` and `inner(x, Ax)` is not small when the test fails.

**Comment by emstoudenmire** [comment]
Looks good thanks! I just reviewed it in detail; before I was going to suggest exactly that you please implement `inner(MPO,MPS,MPO,MPS)` and rewrite `errorMPOProd` that way, but I see you've now done exactly that.

**Pull request merged**
