### PR TITLE
[ITensors] Index filtering docstring improvements

### PR DESCRIPTION
**Pull request by emstoudenmire**
Add list of most common keyword arguments to functions for filtering indices (commoninds, uniqueinds, etc.). Currently it's not so obvious to users what keyword arguments could be passed, as shown by a recent [forum post](https://itensor.discourse.group/t/string-correlation-function-of-several-sites/1066/4).

### CODE REVIEW

**Comment by emstoudenmire** [comment]
@mtfishman please let me know if these docstrings look accurate to you

**Comment by mtfishman** [comment]
Looks good to me, thanks. One suggestion I would have is defining a function:
```julia
function index_filter_kwargs_docstring()
return """
  Optional keyword arguments:
  * tags::String - a tag name or comma separated list of tag names that the returned indices must all have
  * plev::Int - common prime level that the returned indices must all have
  * inds - Index or collection of indices. Returned indices must come from this set of indices.
  """
end
```
and interpolate that into the other docstrings with `$(index_filter_kwargs_docstring())` so if we want to change or update it we just need to update it in one place.

**Comment by emstoudenmire** [comment]
Great, yes I was thinking that very same thing but couldn't remember quite how to do it. I'll make that change.

**Comment by emstoudenmire** [comment]
@mtfishman ok just made that change

**Comment by mtfishman** [comment]
Thanks!

**Pull request merged**
