### PR TITLE
Pass projected operator to Observer measure function

### PR DESCRIPTION
**Pull request by emstoudenmire**
# Description

Pass the "PH" object to the observer system `measure!` function. This can be useful for e.g. monitoring
 the memory usage of `dmrg`.

# Checklist:

- [X] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have added tests that verify the behavior of the changes I made.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by emstoudenmire** [comment]
After adding this I'll add a code example for obtaining the memory usage. Here's the main part of it:
```
mutable struct SizeObserver <: AbstractObserver
end

function ITensors.measure!(o::SizeObserver; bond, half_sweep, psi, projected_operator, kwargs...)
  Mega = 1E6
  if bond==1 && half_sweep==2
    psi_size =  Base.summarysize(psi)/Mega
    PH_size =  Base.summarysize(projected_operator)/Mega
    println("|psi| = $psi_size Mb, |PH| = $PH_size Mb")
  end
end
```

Sample output:
```
|psi| = 0.216384 Mb, |PH| = 0.60824 Mb
After sweep 1 energy=-43.98842364901808  maxlinkdim=10 maxerr=9.61E-06 time=0.088
|psi| = 0.655808 Mb, |PH| = 1.70968 Mb
After sweep 2 energy=-44.10595326327692  maxlinkdim=20 maxerr=7.62E-07 time=0.140
|psi| = 2.130752 Mb, |PH| = 5.43892 Mb
After sweep 3 energy=-44.12610055496431  maxlinkdim=45 maxerr=1.00E-08 time=0.274
|psi| = 3.002608 Mb, |PH| = 7.59888 Mb
After sweep 4 energy=-44.127711130973125  maxlinkdim=53 maxerr=9.99E-09 time=0.475
|psi| = 3.247392 Mb, |PH| = 8.19712 Mb
After sweep 5 energy=-44.127736758690986  maxlinkdim=56 maxerr=9.99E-09 time=0.581
```

**Comment by mtfishman** [comment]
Thanks! I just learned about `Base.format_bytes`:
```julia
julia> Base.format_bytes(1e2)
"100 bytes"

julia> Base.format_bytes(1e5)
"97.656 KiB"

julia> Base.format_bytes(1e8)
"95.367 MiB"

julia> Base.format_bytes(1e11)
"93.132 GiB"
```
Maybe we should also include the Hamiltonian in the example, for completeness? It looks like it isn't passed, maybe we should pass it as `operator`?

**Comment by emstoudenmire** [comment]
Good to learn about `Base.format_bytes` - very nice. 

Agreed about passing the Hamiltonian as `operator` too. 

Regarding the example, did you mean just showing the more complete code including the OpSum etc? I plan to do that in the docs. Or did you mean showing the memory usage of H itself?

**Comment by mtfishman** [comment]
I meant show the memory usage of H as well (and of course show a fully working example, but I assumed you would do that!).

**Comment by emstoudenmire** [comment]
Oh, so it's not so clear we can pass the `operator` for various reasons. Apart from needing to add more code "plumbing", since the core `dmrg` function only takes the `PH` object currently, it's not clear what the operator would be in cases like e.g. a ProjMPOSum of multiple MPOs. So it seems more complicated than it is worth at this time.

**Comment by mtfishman** [comment]
Oh right, I forgot about that. I guess `PH` already should include `H` (where relevant) so from the perspective of `Base.summarysize` there isn't really any need.

**Pull request merged**
